import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile, readdir } from 'node:fs/promises';
import { resolve } from 'node:path';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import {
  checkSegregation, createAuthorizationRequest, createDatasetManifest, createExactPromotionPlan,
  createImpactReport, createRollbackPlan, evaluateReadiness, hashValue, probablePromotable,
  resolveProbable, runDatasetDryRun, simulateGitFlow, validatePlannedDiff,
  validateReadinessPolicy, verifyManifest
} from '../../src/ingestion/index.mjs';
const exec=promisify(execFile);const root=resolve(new URL('../..',import.meta.url).pathname.replace(/^\/(.:)/,'$1'));
const fixturePath='ingestion/fixtures/simulated-promotion/eligible.reviewed.json';const fixture=await readFile(new URL(`../../${fixturePath}`,import.meta.url),'utf8');const fixtureHash=hashValue(fixture);
const rawPolicy={version:1,batch_limit:10,simulated_retention_days:1,cache_ttl_seconds:3600,rerun_policy:'resume_confirmed',dual_approval_required:true,incompatible_roles:[['package_preparer','final_authorizer']],probable_resolution_policy:'human_required',required_authorizer_count:2};const policy=validateReadinessPolicy(rawPolicy);
const manifestInput={dataset:'DATASET-002',batch_id:'dataset-002-synthetic-dry-run',purpose:'dry run sintético',dry_run:true,promotion_authorized:false,allowed_fixtures:[{path:fixturePath,sha256:fixtureHash}],included_items:['cand-synthetic-promotion-001'],excluded_items:[],versions:{pipeline:'A-D'},policy_version:1};
const manifest=()=>createDatasetManifest(manifestInput,rawPolicy);
const planOp={path:'data/jurisprudencia/tjce-7654321-71-2025-8-06-9999.yaml',operation:'add',previous_hash:null,new_hash:'sha256:new',origin:'proposal',proposal_id:'proposal-1',reason:'approved future addition'};

test('manifesto DATASET-002 é determinístico e invariantes são obrigatórios',()=>{assert.deepEqual(manifest(),manifest());assert.match(manifest().manifest_id,/dataset-manifest-sha256/);assert.throws(()=>createDatasetManifest({...manifestInput,dataset:'OTHER'},rawPolicy),{code:'dataset_not_allowed'});assert.throws(()=>createDatasetManifest({...manifestInput,dry_run:false},rawPolicy),{code:'manifest_invalid'});assert.throws(()=>createDatasetManifest({...manifestInput,promotion_authorized:true},rawPolicy),{code:'manifest_invalid'});});
test('allowlist rejeita fixture implícita, glob, diretório e traversal',()=>{for(const path of ['content/file.json','ingestion/fixtures/**','ingestion/fixtures/','ingestion/fixtures/../x'])assert.throws(()=>createDatasetManifest({...manifestInput,allowed_fixtures:[{path,sha256:'x'}]},rawPolicy),{code:'fixture_not_allowed'});});
test('hash divergente e mutação do manifesto bloqueiam',()=>{const value=manifest();assert.throws(()=>verifyManifest(value,{[fixturePath]:'wrong'}),{code:'manifest_invalid'});const changed={...value,purpose:'mutated'};assert.throws(()=>verifyManifest(changed,{[fixturePath]:fixtureHash}),{code:'manifest_changed'});assert.doesNotThrow(()=>verifyManifest(value,{[fixturePath]:fixtureHash}));});
test('parâmetros falham fechado, rejeitam desconhecidos e não contêm segredos',()=>{const missing={...rawPolicy};delete missing.batch_limit;assert.throws(()=>validateReadinessPolicy(missing),{code:'parameter_missing'});assert.throws(()=>validateReadinessPolicy({...rawPolicy,unknown:true}),{code:'parameter_invalid'});assert.throws(()=>validateReadinessPolicy({...rawPolicy,rerun_policy:'https://endpoint'}),{code:'parameter_invalid'});});
test('orquestrador reutiliza sete gates A-D, é determinístico e retomável',async()=>{const calls={};const stages=Object.fromEntries(['foundation','recovery','classification','review','proposal','deduplication','sandbox'].map(name=>[name,async()=>{calls[name]=(calls[name]??0)+1;return{name,ok:true};}]));const one=await runDatasetDryRun({manifest:manifest(),policy,stages});const two=await runDatasetDryRun({manifest:manifest(),policy,stages});assert.equal(one.complete,true);assert.equal(one.run_id,two.run_id);const partial=await runDatasetDryRun({manifest:manifest(),policy,stages,stopAfter:3});const resumed=await runDatasetDryRun({manifest:manifest(),policy,stages,checkpoint:partial.events});assert.equal(resumed.complete,true);assert.equal(calls.foundation,3);});
test('mudança legítima de parâmetro muda identidade',()=>{const other=validateReadinessPolicy({...rawPolicy,batch_limit:9});assert.notEqual(other.identity,policy.identity);assert.notEqual(createDatasetManifest(manifestInput,{...rawPolicy,batch_limit:9}).manifest_id,manifest().manifest_id);});
test('provável sem decisão bloqueia; decisões humanas são versionadas e idempotentes',()=>{assert.equal(probablePromotable([]),false);const base={candidate_id:'cand-probable',decision:'distinct_decision',resolver:{id:'resolver-opaque',role:'duplicate_resolver'},justification:'metadados decisórios distintos',evidence:['synthetic-evidence'],expected_version:0,idempotency_key:'resolution-1'};const first=resolveProbable([],base);assert.equal(first.event.automatic_result,'probable_duplicate');assert.equal(probablePromotable(first.events),true);assert.equal(resolveProbable(first.events,base).idempotent,true);assert.throws(()=>resolveProbable(first.events,{...base,idempotency_key:'other',expected_version:0}),{code:'probable_resolution_stale'});});
test('resoluções exata e retorno não promovem; justificativa, evidência e papel são exigidos',()=>{const base={candidate_id:'c',resolver:{id:'r',role:'duplicate_resolver'},justification:'j',evidence:['e'],expected_version:0,idempotency_key:'k'};for(const decision of ['exact_duplicate','return_for_evidence','exclude_from_batch'])assert.equal(probablePromotable(resolveProbable([],{...base,decision}).events),false);assert.throws(()=>resolveProbable([],{...base,decision:'distinct_decision',evidence:[]}),{code:'probable_unresolved'});assert.throws(()=>resolveProbable([],{...base,decision:'distinct_decision',resolver:{id:'x',role:'observer'}}),{code:'role_not_allowed'});});
test('segregação impede autoautorização e dupla aprovação não é fabricada',()=>{assert.throws(()=>checkSegregation([{identity:'same',role:'package_preparer'},{identity:'same',role:'final_authorizer',real:true}],rawPolicy),{code:'segregation_violation'});assert.throws(()=>checkSegregation([{identity:'prep',role:'package_preparer'},{identity:'auth1',role:'final_authorizer',real:true}],rawPolicy),{code:'dual_approval_missing'});assert.equal(checkSegregation([{identity:'prep',role:'package_preparer'},{identity:'a1',role:'final_authorizer',real:true},{identity:'a2',role:'final_authorizer',real:true}],rawPolicy),true);});
test('plano é fechado e rejeita path, traversal, symlink, caixa e sobrescrita',()=>{const plan=createExactPromotionPlan([planOp]);assert.deepEqual(plan.operations,[planOp]);for(const op of [{...planOp,path:'content/x.yaml'},{...planOp,path:'data/jurisprudencia/../x.yaml'},{...planOp,is_symlink:true},{...planOp,previous_hash:'old'}])assert.throws(()=>createExactPromotionPlan([op]));assert.throws(()=>createExactPromotionPlan([planOp,{...planOp,path:planOp.path.toUpperCase()}]));});
test('diff deve corresponder exatamente ao plano e não pode ser vazio',()=>{const plan=createExactPromotionPlan([planOp]);assert.equal(validatePlannedDiff(plan,[{path:planOp.path}]),true);assert.throws(()=>validatePlannedDiff(plan,[]),{code:'unexpected_diff'});assert.throws(()=>validatePlannedDiff(plan,[{path:'data/jurisprudencia/other.yaml'}]),{code:'unexpected_diff'});});
test('impacto reconcilia contagens e conteúdo proposto não contém operação',()=>{const plan=createExactPromotionPlan([planOp]);const report=createImpactReport({before:10,plan,diff:[{path:planOp.path}]});assert.deepEqual(report.counts,{before:10,after:11,added:1,blocked:0});assert.ok(report.invariants.includes('promotion_authorized_false'));assert.doesNotMatch(fixture,/confidence|queue|authorization|promotion_authorized/);});
test('rollback corresponde um a um e em ordem reversa',()=>{const ops=[planOp,{...planOp,path:'data/jurisprudencia/tjce-1234567-03-2025-8-90-0001.yaml',new_hash:'two'}];const plan=createExactPromotionPlan(ops);const rollback=createRollbackPlan(plan);assert.equal(rollback.operations.length,plan.operations.length);assert.equal(rollback.operations[0].path,ops[1].path);});
test('readiness produz NO_GO, CONDITIONAL_GO e GO sem autorizar',()=>{const no=evaluateReadiness([{code:'technical',status:'failed'}]);const conditional=evaluateReadiness([{code:'dry_run',status:'passed'}],['real_authorizers_missing']);const go=evaluateReadiness([{code:'dry_run',status:'passed'}]);assert.equal(no.decision,'NO_GO');assert.equal(conditional.decision,'CONDITIONAL_GO');assert.equal(go.decision,'GO');for(const value of [no,conditional,go])assert.equal(value.promotion_authorized,false);});
test('pedido é completo, não executável e não fabrica aceite',()=>{const rollback=createRollbackPlan(createExactPromotionPlan([planOp]));const request=createAuthorizationRequest({packageHash:'sha256:package',scope:[planOp.path],requiredRoles:['final_authorizer','final_authorizer'],risks:['synthetic_only'],rollbackPlanId:rollback.rollback_plan_id,validUntil:'2026-08-09T00:00:00Z'});assert.equal(request.authorization_requested,true);assert.equal(request.promotion_authorized,false);assert.ok(request.scope.length&&request.risks.length&&request.required_roles.length);assert.doesNotMatch(JSON.stringify(request),/signature|signed|accepted|approved|token/i);});
test('Git simulado é descartável, sem remote e não altera estado real',async()=>{const before=(await exec('git',['rev-parse','HEAD'],{cwd:root})).stdout.trim();const branch=(await exec('git',['branch','--show-current'],{cwd:root})).stdout.trim();const plan=createExactPromotionPlan([planOp]);const result=await simulateGitFlow({repoRoot:root,plan,contents:{[planOp.path]:'synthetic: true\n'}});assert.equal(result.remotes,'');assert.equal(result.branch,'simulated/dataset-002');assert.match(result.message,/SIMULATION ONLY/);assert.match(result.author,/Synthetic/);assert.equal((await exec('git',['rev-parse','HEAD'],{cwd:root})).stdout.trim(),before);assert.equal((await exec('git',['branch','--show-current'],{cwd:root})).stdout.trim(),branch);assert.deepEqual((await readdir(new URL('../../ingestion/dry-runs/',import.meta.url))).filter(n=>n!=='.gitkeep'),[]);});
test('rollback Git limpa também após falha induzida',async()=>{const plan=createExactPromotionPlan([planOp]);await assert.rejects(simulateGitFlow({repoRoot:root,plan,contents:{[planOp.path]:'x'},induceFailure:true}),/induced/);assert.deepEqual((await readdir(new URL('../../ingestion/dry-runs/',import.meta.url))).filter(n=>n!=='.gitkeep'),[]);});
test('artefatos readiness ficam fora de dist',async()=>{const files=await readdir(new URL('../../dist/',import.meta.url),{recursive:true});assert.equal(files.some(f=>/(authorization-request|dry-run|readiness|promotion-plan)/i.test(f)),false);});
