version: 1
aliases:
  rmc: [reserva de margem consignavel, reserva de margem consignável]
  rcc: [reserva de cartao consignado, reserva de cartão consignado]
  consentimento: [vicio de vontade, vício de vontade, vicio de consentimento, vício de consentimento]
